# Generated by Django 2.1.7 on 2021-11-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='address_line_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='office',
            name='openweathermap_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='office',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='office',
            name='image',
            field=models.ImageField(upload_to='huddl/images/'),
        ),
    ]
